name: Manual Release and Build

on:
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Bump version number
        run: |
          # Example: script or command to bump version number
          ./bump_version.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit version bump
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@users.noreply.github.com'
          git add .
          git commit -m "Bump version to [new version]"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build plugin zip
        run: |
          mkdir -p build
          cp -r sermon-filter-plugin build/
          cd build
          zip -r sermon-filter-plugin.zip sermon-filter-plugin

      - name: Upload plugin zip
        uses: actions/upload-artifact@v3
        with:
          name: sermon-filter-plugin
          path: build

      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: "v${{ steps.bump-version.outputs.new_version }}"
          release_name: "Release ${{ steps.bump-version.outputs.new_version }}"
          body: "Release notes for version ${{ steps.bump-version.outputs.new_version }}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
